apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  ports:
  - nodePort: 31472
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
  type: LoadBalancer

