apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins-internal
spec:
  ports:
  - name: master
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: agent
    port: 50000
    protocol: TCP
    targetPort: 50000
  - name: jnlp
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: jenkins
  type: ClusterIP
