apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  labels:
{{ include "jenkins.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "jenkins.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "jenkins.selectorLabels" . | indent 8 }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: jenkins
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
          name: ui
        - containerPort: 50000
          name: agent
        volumeMounts:
        - mountPath: "/var/jenkins_home"
          name: {{ .Values.persistentVolumeClaim.name }}
      volumes:
      - name: {{ .Values.persistentVolumeClaim.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim.name }}
