apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "jenkins.labels" . | indent 4 }}
  name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  ports:
  - nodePort: 31472
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
{{ include "jenkins.selectorLabels" . | indent 4 }}
  type: LoadBalancer