apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "jenkins.labels" . | indent 4 }}
  name: {{ .Chart.Name }}-{{ .Release.Name }}-internal
spec:
  ports:
  - name: master
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: agent
    port: 50000
    protocol: TCP
    targetPort: 50000
  - name: jnlp
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
{{ include "jenkins.selectorLabels" . | indent 4 }}
  type: ClusterIP
