{{- if eq .Values.persistentVolumeClaim.isExist true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
{{- end }}
